### ISSUE TITLE
Fails to build with cargo_metadata 0.10

### ISSUE THREAD

**Issue by sdroege** [EmbarkStudios/krates#10]
60c374015bcf7e548e52585b51bf6bf0a91fcf12 worked around an accidental semver breakage in `cargo_metadata` 0.10.1, which was yanked in the meantime and re-released as 0.11.

This means that now `krates` fails to build against `cargo_metadata` 0.10.0. Either needs to be updated to 0.11 or 60c374015bcf7e548e52585b51bf6bf0a91fcf12 has to be reverted.

If `semver` or any `cargo_metadata` type is part of the public API of this crate then the former would require updating the `krates` version to 0.4.

**Comment by sdroege** [comment]
Thanks for the fast response. Unless you yank 0.3.1 of krates this will nonetheless break everything that currently depends on krates 0.3 and is not updated yet. Please either yank it, or upload a 0.3.2 that simply downgrades the semver dependency to 0.9.

**Comment by Jake-Shadle** [comment]
Yah, I'll just yank 0.3.1. This was rather annoying, but I do enjoy the irony of this being because of the semver crate.

**Comment by sdroege** [comment]
Indeed :) Thanks again!

**Comment by sdroege** [comment]
And the very same problem in extension also exists with cargo-deny 0.7.1. Want me to create an issue for that or will you take care of that?

**Comment by Jake-Shadle** [comment]
There is an existing issue I just reopened, thanks though!
