### ISSUE TITLE
Unworking rust attribute

### ISSUE THREAD

**Issue by m0ssc0de** [EmbarkStudios/krates#13]
**Describe the bug**

- `src\lib.rs:305:1`
- `#[allow(clippy::reversed_empty_ranges)]`

This OuterAttribute will trigger compiler output a error.

**To Reproduce**
1. `git clone https://github.com/EmbarkStudios/krates.git`
2. `cd krates`
3. `cargo build`

**Expected behavior**
It should be successfully compiled.

**Screenshots**
```
$ cargo build
   Compiling krates v0.4.1 (***\krates)
error: attributes are not yet allowed on `if` expressions
   --> src\lib.rs:305:21
    |
305 |                     #[allow(clippy::reversed_empty_ranges)]
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `krates`.

To learn more, run the command again with --verbose.
```

**Device:**
 - OS: win10

**Additional context**

**Comment by Jake-Shadle** [comment]
I think you are using an old rustlang version, this works perfectly fine in 1.45.0.

**Comment by m0ssc0de** [comment]
> I think you are using an old rustlang version, this works perfectly fine in 1.45.0.

Yes. After updating to 1.45.0, it works. Thanks.
