### ISSUE TITLE
`cargo metadata` incorrectly adds weak dependencies

### ISSUE THREAD

**Issue by joshtriplett** [EmbarkStudios/krates#41]
**Describe the bug**

`cargo deny check bans` errors out saying a banned package appears in dependencies, even if that package only appears in a weak dependency feature that isn't activated.

**To Reproduce**
1. Create a crate that depends on `git2` version `0.14.4`, with `default-features = false`, and `features = ["zlib-ng-compat"]`.
2. Run `cargo tree` and observe no `libssh2-sys` or `openssl-sys` dependency.
3. Create a `deny.toml` that bans `openssl-sys`.
4. Run `cargo deny check bans`, and get this output:

```
warning[B009]: direct parent 'libssh2-sys = 0.2.23' of banned crate 'openssl-sys = 0.9.73' was not marked as a wrapper
   ┌─ /path/to/project/deny.toml:30:14
   │
30 │     { name = "openssl-sys" },
   │              ^^^^^^^^^^^^^ banned here
   │
   = openssl-sys v0.9.73
     └── libssh2-sys v0.2.23
         └── libgit2-sys v0.13.4+1.4.2
             └── git2 v0.14.4
                 └── project v0.1.0
```

**Expected behavior**

`cargo deny check bans` should understand that there's no dependency on `openssl-sys` (or `libssh2-sys`) here.

**Comment by Jake-Shadle** [comment]
Resolved by #42
